# Generated by Django 3.2.6 on 2022-01-31 10:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ipmi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('ssh_key_name', models.TextField()),
                ('ip_to_allow', models.TextField()),
                ('user', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='ipmi', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'IPMI',
                'permissions': [('view_ipmi', 'Can use IPMI')],
                'default_permissions': [],
            },
        ),
    ]
